name: Daily Poetic Motivation

on:
  schedule:
    - cron: '0 7 * * *'  # 9 AM Amsterdam time (UTC+2)
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with write token
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate poetic motivation with OpenRouter
        run: |
          RESPONSE=$(curl -s https://openrouter.ai/api/v1/chat/completions \
            -H "Authorization: Bearer ${{ secrets.OPENROUTER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "openchat/openchat-7b:free",
              "messages": [
                {"role": "user", "content": "Write a short, poetic motivational message to inspire someone working alone on a long-term creative or technical project. Keep it under 25 words."}
              ]
            }')
          MESSAGE=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')
          echo "$(date): $MESSAGE" >> progress.md
          echo "MESSAGE=$MESSAGE" >> $GITHUB_ENV

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add progress.md
          git commit -m "Auto: $MESSAGE" || echo "No changes to commit"
          git push
