name: Tree Growth

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours (00:00, 06:00, 12:00, 18:00 UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate and commit motivation
        run: |
          # 15% chance to skip this run
          if [ $((RANDOM % 100)) -lt 15 ]; then
            echo "Randomly skipping this run (15% chance)"
            exit 0
          fi
          
          # Determine number of commits (1-4)
          COMMIT_COUNT=$((RANDOM % 4 + 1))
          echo "Will make $COMMIT_COUNT commit(s)"
          
          # Tree emoji variations
          TREES=("🌲" "🌳")
          
          # Generate all trees for this run
          ALL_TREES=""
          for ((i=1; i<=$COMMIT_COUNT; i++)); do
            # Determine number of trees in this forest (1-4)
            TREE_COUNT=$((RANDOM % 4 + 1))
            
            # Generate forest by combining random tree emojis
            for ((j=1; j<=$TREE_COUNT; j++)); do
              # Select random tree emoji with true randomness
              TREE_INDEX=$((RANDOM % ${#TREES[@]}))
              TREE="${TREES[$TREE_INDEX]}"
              
              # Add to all trees with space separator
              if [ -z "$ALL_TREES" ]; then
                ALL_TREES="$TREE"
              else
                ALL_TREES="$ALL_TREES $TREE"
              fi
            done
          done
          
          # Shuffle the final tree sequence for more natural randomness
          SHUFFLED_TREES=$(echo "$ALL_TREES" | tr ' ' '\n' | shuf | tr '\n' ' ' | sed 's/ $//')
          ALL_TREES="$SHUFFLED_TREES"
          
          # Check if progress.md exists and get the last line
          if [ -f "progress.md" ]; then
            LAST_LINE=$(tail -n 1 progress.md 2>/dev/null || echo "")
            
            # If last line starts with "- " and has less than 20 trees, add to it
            if [[ "$LAST_LINE" =~ ^- ]] && [[ $(echo "$LAST_LINE" | wc -w) -lt 20 ]]; then
              # Remove the "- " prefix and count existing trees
              EXISTING_TREES=$(echo "$LAST_LINE" | sed 's/^- //')
              EXISTING_COUNT=$(echo "$EXISTING_TREES" | wc -w)
              
              # Calculate how many trees we can add to this line
              REMAINING_SPACE=$((20 - EXISTING_COUNT))
              TREES_TO_ADD=$(echo "$ALL_TREES" | cut -d' ' -f1-$REMAINING_SPACE)
              
              # Update the last line
              sed -i '$s/.*/- '"$EXISTING_TREES $TREES_TO_ADD"'/' progress.md
              
              # If we have more trees than can fit, start a new line
              if [ $(echo "$ALL_TREES" | wc -w) -gt $REMAINING_SPACE ]; then
                REMAINING_TREES=$(echo "$ALL_TREES" | cut -d' ' -f$((REMAINING_SPACE + 1))-)
                echo "- $REMAINING_TREES" >> progress.md
              fi
            else
              # Start a new line
              echo "- $ALL_TREES" >> progress.md
            fi
          else
            # File doesn't exist, start fresh
            echo "- $ALL_TREES" >> progress.md
          fi
          
          # Commit all trees at once
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add progress.md
          git commit -m "🌲 Auto: Growing forest" || echo "No changes to commit"
          
          # Push all commits
          git push || echo "Push failed"
