name: Tree Growth

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours (00:00, 06:00, 12:00, 18:00 UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate and commit motivation
        run: |
          # 15% chance to skip this run
          if [ $((RANDOM % 100)) -lt 15 ]; then
            echo "Randomly skipping this run (15% chance)"
            exit 0
          fi
          
          # Determine number of commits (1-4)
          COMMIT_COUNT=$((RANDOM % 4 + 1))
          echo "Will make $COMMIT_COUNT commit(s)"
          
          # Tree emoji variations
          TREES=("🌲" "🌳")
          
          # Generate all trees for this run
          ALL_TREES=""
          for ((i=1; i<=$COMMIT_COUNT; i++)); do
            # Determine number of trees in this forest (1-4)
            TREE_COUNT=$((RANDOM % 4 + 1))
            
            # Generate forest by combining random tree emojis
            FOREST=""
            for ((j=1; j<=$TREE_COUNT; j++)); do
              # Select random tree emoji
              TREE_INDEX=$((RANDOM % ${#TREES[@]}))
              TREE="${TREES[$TREE_INDEX]}"
              
              if [ $j -eq 1 ]; then
                FOREST="$TREE"
              else
                # Add space between trees
                FOREST="$FOREST $TREE"
              fi
            done
            
            # Add to all trees with space separator
            if [ $i -eq 1 ]; then
              ALL_TREES="$FOREST"
            else
              ALL_TREES="$ALL_TREES $FOREST"
            fi
          done
          
          # Add all trees to file in one line
          echo "- $ALL_TREES" >> progress.md
          
          # Commit all trees at once
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add progress.md
          git commit -m "🌲 Auto: Growing forest" || echo "No changes to commit"
          
          # Push all commits
          git push || echo "Push failed"
