name: Tree Growth

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours (00:00, 06:00, 12:00, 18:00 UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate and commit trees
        run: |
          # Determine number of commits for this session (0-4)
          # This represents how many trees we'll plant in this 6-hour period
          COMMIT_COUNT=$((RANDOM % 5))  # 0, 1, 2, 3, or 4
          echo "Will make $COMMIT_COUNT commit(s) in this session"
          
          # If no commits, just exit (no trees planted this session)
          if [ $COMMIT_COUNT -eq 0 ]; then
            echo "No trees to plant this session - taking a break!"
            exit 0
          fi
          
          # Tree emoji variations for visual variety
          TREES=("🌲" "🌳")
          
          # Make each commit individually, adding one tree per commit
          for ((i=1; i<=$COMMIT_COUNT; i++)); do
            echo "Making commit $i of $COMMIT_COUNT..."
            
            # Select a random tree emoji for this commit
            TREE_INDEX=$((RANDOM % ${#TREES[@]}))
            TREE="${TREES[$TREE_INDEX]}"
            
            # Check if progress.md exists and get the last line
            if [ -f "progress.md" ]; then
              LAST_LINE=$(tail -n 1 progress.md 2>/dev/null || echo "")
              
              # If last line starts with "- " and has less than 20 trees, add to it
              if [[ "$LAST_LINE" =~ ^- ]] && [[ $(echo "$LAST_LINE" | wc -w) -lt 20 ]]; then
                # Remove the "- " prefix and add the new tree
                EXISTING_TREES=$(echo "$LAST_LINE" | sed 's/^- //')
                UPDATED_TREES="$EXISTING_TREES $TREE"
                
                # Update the last line with the new tree
                sed -i '$s/.*/- '"$UPDATED_TREES"'/' progress.md
              else
                # Start a new line with just this tree
                echo "- $TREE" >> progress.md
              fi
            else
              # File doesn't exist, start fresh with this tree
              echo "- $TREE" >> progress.md
            fi
            
            # Configure git for this commit
            git config user.name "teoderizzoai"
            git config user.email "teo.derizzo.ai@gmail.com"
            
            # Add and commit this single tree
            git add progress.md
            git commit -m "🌲 Auto: Planted tree #$i of $COMMIT_COUNT" || echo "No changes to commit"
            
            echo "Committed tree $i: $TREE"
          done
          
          # Push all commits at once
          echo "Pushing $COMMIT_COUNT commits..."
          git push || echo "Push failed"
          
          echo "Session complete! Planted $COMMIT_COUNT trees across $COMMIT_COUNT commits."
